win-msys:
	g++ main.cpp -o build/main.exe -IC:\msys64\ucrt64\include -LC:\msys64\ucrt64\lib -lmingw32 -lSDL2main -lSDL2

empp:
	em++ main.cpp -o index.html -s USE_SDL=2 -s FORCE_FILESYSTEM=1 -s EXPORTED_FUNCTIONS="['run']"

dummy:

