win-msys:
	g++ main.cpp -o build/main.exe -IC:\msys64\ucrt64\include -LC:\msys64\ucrt64\lib -lmingw32 -lSDL2main -lSDL2

empp:
	em++ main.cpp -o build/index.html -Os -lidbfs.js -sUSE_SDL=2 -sFORCE_FILESYSTEM=1 -sEXPORTED_RUNTIME_METHODS='["FS"]'

dummy:

